import Head from "next/head";
import { Container, Typography, Box } from "@mui/material";
import BreadCrumbs from "@/components/BreadCrumbs";

export default function Home() {
  return (
    <>
      <Head>
        <title>S-Control</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ ml: 2 }}>
        <BreadCrumbs items={null} />
      </Box>
      <Container>
        <Typography variant="h1" sx={{ textTransform: "uppercase"}}>Co nas wyróżnia</Typography>
        <Typography variant="body1">Some text...</Typography>
      </Container>
    </>
  );
}
